#!/usr/bin/env perl

# Copyright © 2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

use strict;
use warnings;

my ($login, $name, $email);

sub flush
{
    if (defined $login) {
        print "$login = $name <$email>\n";
        ($login, $name, $email) = ();
    }
    return;
}

while (<STDIN>) {
    if (/^Login: (\S+)\s+Name: (\S.*)$/) {
        flush;
        $login = $1;
        $name = $2;
        $name =~ s/^\s*|\s*$//g;
        $email = "$login\@localhost"
    }
    if (/^Mail forwarded to (\S+)/) {
        $email = $1;
    }
}
flush;

# vim:ts=4 sts=4 sw=4 et
